parse_config:
  zmk_combos:
    cplck: { draw_separate: true }
    co_all: { draw_separate: true }
    co_cp: { draw_separate: true }
    co_paste: { draw_separate: true }
    co_cut: { draw_separate: true }

  raw_binding_map:
    '&trans': ' '
    '&soft_off': Soft Off

    '&bt BT_SEL 0': BT 1
    '&bt BT_SEL 1': BT 2
    '&bt BT_SEL 2': BT 3
    '&bt BT_SEL 3': BT 4
    '&bt BT_SEL 4': BT 5

    '&kp LG(LC(LEFT))': Desk Left
    '&kp LG(LC(RIGHT))': Desk Right
    '&kp LG(L)': Lock
    '&kp LC(LA(DEL))': Ctl Alt Del

    '&kp LC(A)': Select All
    '&kp LC(X)': Cut
    '&kp LC(C)': Copy
    '&kp LC(V)': Paste

  zmk_keycode_map:
    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    SPACE: ␣
    BSPC: ⌫
    RET: ⏎
    TAB: ↹
    DEL: ⌦

    C_PP: ⏯
    C_PREV: ⏮ 
    C_NEXT: ⏭

    HOME: Home
    END: End
    PG_UP: Page Up
    PG_DOWN: Page Down

    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: Alt
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _

draw_config:
  footer_text: 'Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>'
  dark_mode: auto