parse_config:
  zmk_combos:
    combo_cplck: { draw_separate: true }
    combo_all: { align: 'bottom' }
    combo_grave: { align: 'top' }
    combo_capword: { align: 'top' }
    combo_dqt: { align: 'bottom' }
    combo_slash: { align: 'bottom' }
    combo_cdup:
      draw_separate: true
      key: '../'
    combo_ion: 
      draw_separate: true 
      key: ion
    combo_rptl: 
      draw_separate: true 
      key: Key Repeat
    combo_percent:
      align: top
      key: '%'

    # Combos with HRM hold-taps, don't draw the hold on bottom
    combo_lpar: { key: '(' }
    combo_rpar: { key: ')' }
    combo_lbrc: { key: '{' }
    combo_rbrc: { key: '}' }
    combo_lbkt: { key: '[' }
    combo_rbkt: { key: ']' }
    combo_del:
      draw_separate: true
      key: ⌦
    combo_esc:
      draw_separate: true
      key: Esc
    combo_ret:
      draw_separate: true
      key: ⏎
    combo_tab:
      draw_separate: true
      key: ↹

  raw_binding_map:
    '&trans': ' '
    '&soft_off': Soft Off
    '&sys_reset': Reset
    '&bootloader': Boot
    '&fatarrow': =>
    '&caps_word': Caps Word
    '&swapper': Win Next
    '&ion': '"ion"'
    '&num_word': Num Word
    '&mmv MOVE_UP': Mouse ↑
    '&mmv MOVE_DOWN': Mouse ↓
    '&mmv MOVE_LEFT': Mouse ←
    '&mmv MOVE_RIGHT': Mouse →
    '&msc MOVE_UP': Scroll Up
    '&msc MOVE_DOWN': Scroll Down
    '&sftclk': Click

    '&bt BT_SEL 0': BT 1
    '&bt BT_SEL 1': BT 2
    '&bt BT_SEL 2': BT 3
    '&bt BT_SEL 3': BT 4
    '&bt BT_SEL 4': BT 5
    '&ext_power EP_ON': Ext Power On

    '&kp LG(LC(LEFT))': Desk Left
    '&kp LG(LC(RIGHT))': Desk Right
    '&kp LG(L)': Lock
    '&kp LA(F4)': Win Close
    '&kp LC(LA(DEL))': C+A+⌦
    '&kp LC(BSPC)': ⌫ Word

    '&kp LC(A)': Select All
    '&kp LC(X)': Cut
    '&kp LC(C)': Copy
    '&kp LC(V)': Paste

  zmk_keycode_map:
    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    SPACE: ␣
    BSPC: ⌫
    RET: ⏎
    TAB: ↹
    DEL: ⌦
    ESC: Esc

    C_PP: ⏯
    C_PREV: ⏮ 
    C_NEXT: ⏭

    CAPS: Caps Lock
    HOME: Home
    END: End
    PG_UP: Page Up
    PG_DN: Page Down
    PG_DOWN: Page Down

    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: Alt
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _

draw_config:
  footer_text: 'Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>'
  dark_mode: auto
