manifest:
  remotes:
    - name: hendstephen
      url-base: https://github.com/hendstephen
  projects:
    - name: zmk
      remote: hendstephen 
      revision: main
      import: app/west.yml
  self:
    path: config