manifest:

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      revision: v0.2
    # For ZMK modules
    - name: urob
      url-base: https://github.com/urob
      revision: v0.2
    # For nice-view-gem
    - name: m165437
      url-base: https://github.com/M165437
      revision: main
      
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
      revision: v0.2

    # Temporarily overload Zephyr until
    # https://github.com/zmkfirmware/zephyr/pull/40 is merged.
    - name: zephyr
      remote: urob
      revision: v3.5.0+zmk-fixes
      clone-depth: 1
      import:
        # Only enable most commonly used boards. For less common hardware one
        # may need to enable additional modules.
        name-allowlist:
          - cmsis
          - hal_nordic
          - hal_rpi_pico
          - hal_stm32
          - lvgl
          - tinycrypt

    # - name: zmk
    #   remote: urob # or zmkfirmware, see comment below
    #   revision: v0.2+fix-child-nodes
    #   import: app/west.yml

    - name: zmk-adaptive-key
      path: modules/zmk/adaptive-key
      remote: urob
      revision: v0.2
    - name: zmk-auto-layer
      path: modules/zmk/auto-layer
      remote: urob
      revision: v0.2
    - name: zmk-helpers
      path: modules/zmk/helpers
      remote: urob
      revision: v0.2

    - name: nice-view-gem
      remote: m165437
      revision: main

  self:
    path: config