manifest:
  defaults:
    remote: urob
    revision: v0.3.0

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # For ZMK modules
    - name: urob
      url-base: https://github.com/urob
    # For nice-view-gem
    - name: m165437
      url-base: https://github.com/M165437

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml

    # - name: zmk
    #   remote: urob # or zmkfirmware, see comment below
    #   revision: v0.2+fix-child-nodes
    #   import: app/west.yml

    - name: zmk-adaptive-key # For magic key
    - name: zmk-auto-layer
    - name: zmk-helpers

    - name: nice-view-gem
      remote: m165437

  self:
    path: config
