manifest:

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # For ZMK modules
    - name: urob
      url-base: https://github.com/urob
    # For nice-view-gem
    - name: m165437
      url-base: https://github.com/M165437
      
  projects:
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: main
    #   import: app/west.yml

    - name: zmk
      remote: urob # or zmkfirmware, see comment below
      revision: v0.2+fix-child-nodes
      import: app/west.yml
    - name: zmk-adaptive-key
      remote: urob
      revision: v0.2 # set to same as ZMK version above

    - name: zmk-auto-layer
      remote: urob
      revision: main
    - name: zmk-helpers
      remote: urob
    - name: nice-view-gem
      remote: m165437
      revision: main

  self:
    path: config