# Draw keymap diagrams using keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - keymap-drawer/config.yaml
      - .github/workflows/draw-keymaps.yml

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      # keymap_patterns: config/*.keymap
      keymap_pattenrs: config/corne.keymap
      config_path: keymap-drawer/config.yaml
      output_folder: keymap-drawer
      install_branch: main
      amend_commit: true
      west_config_path: 'config' # This pulls external zephyr modules so keymap drawer can see them
      # commit_message: "[Draw] ${{ github.event.head_commit.message }}"